name: release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 请选择版本号更新类型。
         自动版本：根据提交信息自动递增版本号；
         固定版本：版本号固定为 package.json 中的 version 字段；
         跳过版本：跳过版本号更新。
        required: true
        type: choice
        options:
          - 自动版本
          - 固定版本
          - 跳过版本

jobs:
  release:
    if: github.ref_name == 'v1.x'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build

      - name: Code lint
        run: npm run lint

      - name: Unit test
        run: npm run test

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Version bump
        run: node scripts/ci-version-bump.cjs ${{github.event.inputs.version-type}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: FrontEndDev-org/publish-node-package-action@v5
